# Clippy configuration
msrv = "1.85"
warn-on-all-wildcard-imports = true
allow-expect-in-tests = true
allow-unwrap-in-tests = true
allow-dbg-in-tests = true
allow-print-in-tests = true
max-fn-params-bools = 3
max-struct-bools = 3
too-many-arguments-threshold = 8
type-complexity-threshold = 250
single-char-binding-names-threshold = 4
too-many-lines-threshold = 200
array-size-threshold = 512000
vec-box-size-threshold = 4096
enum-variant-size-threshold = 200
future-size-threshold = 16384
unnecessary-box-size = 128
